# Generated by Django 6.0.3 on 2026-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='ชื่อลูกค้า')),
                ('phone_number', models.CharField(max_length=20, verbose_name='เบอร์ติดต่อ')),
                ('device_model', models.CharField(max_length=150, verbose_name='รุ่นอุปกรณ์ (Device)')),
                ('issue_description', models.TextField(verbose_name='อาการเสีย (Corruption Details)')),
                ('status', models.CharField(choices=[('PENDING', 'รอรับเครื่อง (Awaiting Arrival)'), ('INSPECTING', 'กำลังตรวจสอบ (Diagnosing Machine Spirit)'), ('WAITING_PARTS', 'รออะไหล่ (Awaiting Sacred Parts)'), ('REPAIRING', 'กำลังซ่อมแซม (Performing Rite of Repair)'), ('COMPLETED', 'ซ่อมเสร็จสิ้น (Sanctified & Ready)'), ('DELIVERED', 'ส่งมอบแล้ว (Returned to Owner)')], default='PENDING', max_length=20, verbose_name='สถานะงานซ่อม')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้งซ่อม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตสถานะล่าสุด')),
            ],
        ),
    ]
