# Generated by Django 6.0.3 on 2026-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('profile_picture', models.ImageField(upload_to='profile_pics/', verbose_name='รูปโปรไฟล์')),
                ('bio', models.TextField(verbose_name='ประวัติส่วนตัว')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram URL')),
            ],
        ),
    ]
