# Generated by Django 6.0.3 on 2026-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, help_text='พิมพ์ประวัติหรือข้อมูลร้านตรงนี้ได้เลย', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
