# Generated by Django 6.0.3 on 2026-03-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_bio_userprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='knowledge_archives',
            field=models.TextField(blank=True, null=True, verbose_name='คลังความรู้ (Knowledge Archives)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_history',
            field=models.TextField(blank=True, null=True, verbose_name='ประวัติการรับใช้ (Service History)'),
        ),
    ]
