# Generated by Django 6.0.3 on 2026-03-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_knowledge_archives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faction',
            field=models.CharField(default='Volkgaard Tech', max_length=100, verbose_name='สังกัด (Faction)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Terra (Earth)', max_length=100, verbose_name='สถานที่ตั้ง'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='IT Support Technician', max_length=100, verbose_name='บทบาท (Role)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site_title',
            field=models.CharField(default='Tech-Priest: รวินท์ งามเลิศ (Volk)', max_length=200, verbose_name='หัวข้อหน้าเว็บ'),
        ),
    ]
