# Generated by Django 6.0.3 on 2026-03-22 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_faction_userprofile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อข่าว')),
                ('content', models.TextField(verbose_name='เนื้อหาข่าว')),
                ('is_published', models.BooleanField(default=True, verbose_name='สถานะเผยแพร่ (ขึ้นเว็บ)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ประกาศ')),
            ],
            options={
                'verbose_name': 'ประกาศข่าวสาร',
                'verbose_name_plural': 'กระดานข่าวสาร (News)',
                'ordering': ['-created_at'],
            },
        ),
    ]
