# Generated by Django 6.0.3 on 2026-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='รูปภาพประกอบ (ถ้ามี)'),
        ),
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, help_text='ก๊อปปี้ลิงก์ YouTube มาวางได้เลยครับ', max_length=500, null=True, verbose_name='ลิงก์วิดีโอ (เช่น YouTube)'),
        ),
    ]
